### ISSUE TITLE
Website renders badly in smaller desktop viewports.

### ISSUE THREAD

**Issue by Lukasa** [PyconUK/2017.pyconuk.org#6]
Specifically, the blue snake covers important text!

![screen shot 2017-06-15 at 08 23 04](https://user-images.githubusercontent.com/1382556/27169941-f833f5e6-51a3-11e7-905e-a805dd50a1f0.png)

**Comment by inglesp** [comment]
So I haven't been able to reproduce this at all (changing the viewport size makes the blue snake duck its head) but #9 should fix it.

**Comment by inglesp** [comment]
@Lukasa, how does this look with the latest version of the live site?

**Comment by Lukasa** [comment]
Seems fine now!

**Comment by meshy** [comment]
I'm still getting odd behaviour at some screen widths:

![screenshot from 2017-07-12 16-28-16](https://user-images.githubusercontent.com/767671/28125661-257bc5d4-671f-11e7-9a21-81ba45d56360.png)

![screenshot from 2017-07-12 16-28-43](https://user-images.githubusercontent.com/767671/28125688-38285968-671f-11e7-8cac-15a6f0444442.png)

**Comment by inglesp** [comment]
@meshy Do re-open if you think it's worth trying to fix.  If so, is there anything you could provide for debugging?

**Comment by meshy** [comment]
I do think it's likely to be annoying for some people.

I've made a gif to highlight how the snake position changes with the viewport width:

![snakes-on-text-compressed](https://user-images.githubusercontent.com/767671/28127171-999da33e-6723-11e7-934c-032f357d5b4d.gif)

The biggest issue is the blue snake, but the yellow one does get in the way of the "led" at times too.

**Comment by inglesp** [comment]
@hawkz, could you take a look?

**Comment by hawkz** [comment]
Depending on the design/plan next year we could definitely expand the tests to cover 'all' widths instead of just key dimensions
